### ISSUE TITLE
Tasker conditions are only getting tiggered when starting up while the build in conditions work

### ISSUE THREAD

**Issue by LenaWil** [twofortyfouram/android-display-condition-plugin-for-locale#1]
First of all, this might be due to a bug in EMUI, the power saving settings are sometime slightly too aggressive, but I did not have another phone to test it.

# Steps to reproduce
1. install this app and Tasker 5.0b
2. Add a profile to ...
1. * play a sound (1) when the display off condition of this app happens
1. * play a sound (2) when the display on condition of this app happens
1. * play a sound (3) when the display off condition of the native tasker condition happens
1. * play a sound (4) when the display on condition of the native tasker condition happens
3. Save
4. Turn display off.
5. Turn display on.

# What did you expect to happen
I expected sound 2,4,3,1,2 and 4 to play, in that order.

# What happend
Sound 2,4,3,4 played, in that order.

# Enviroment
Device: Huawei Honor 8
OS: Android 7.0, Emui 5.0

**Comment by ccjernigan** [comment]
@TijmenW Thanks for writing.  I'm the developer of [Locale](https://play.google.com/store/apps/details?id=com.twofortyfouram.locale).

For the best support with this issue, I recommend contacting the developer of [Tasker](https://play.google.com/store/apps/details?id=net.dinglisch.android.taskerm), who has a support email address listed on the Google Play store.

**Comment by ccjernigan** [comment]
@TijmenW Do you have a reproducible test case involving Locale?

**Comment by ccjernigan** [comment]
@TijmenW Also one other suggestion would be to look at the `logcat` output of the example plug-in, as it should indicate when it is receiving Intents from the host application.
